name: Build Flatpak

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run nightly builds at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build Flatpak
      uses: flathub-infra/flatpak-github-actions/flatpak-builder@v6.3
      with:
        bundle: bluebubbles-client.flatpak
        manifest-path: com.github.bluebubbles.client.yml
        cache-key: flatpak-builder-${{ github.sha }}
    
    - name: Upload Flatpak artifact
      uses: actions/upload-artifact@v4
      with:
        name: flatpak-package
        path: bluebubbles-client.flatpak

  release-flatpak:
    needs: flatpak
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    name: Release Flatpak
    
    steps:
    - name: Download Flatpak artifact
      uses: actions/download-artifact@v4
      with:
        name: flatpak-package
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: flatpak-nightly-${{ github.run_number }}
        name: Flatpak Nightly Build ${{ github.run_number }}
        body: |
          Automated nightly Flatpak build of BlueBubbles Client
          
          **Installation:**
          ```bash
          flatpak install --user bluebubbles-client.flatpak
          ```
          
          **Note**: This is a nightly build and may contain experimental features or bugs.
        draft: false
        prerelease: true
        files: |
          bluebubbles-client.flatpak
